version: 2
jobs:
  build:
    working_directory: ~/ts-commonutil
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install

      - save_cache:
          key: dependency-cache-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Type Check
          command: yarn typecheck

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test --detectOpenHandles --force-exit

      - run:
          name: Collect Test Coverage
          command: yarn test:coverage --detectOpenHandles --force-exit

      - run:
          name: Upload Test Coverage
          command: yarn codecov

      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
