name: Check

on:
  push:
    branches:
      - main
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: 'yarn.lock'
    - run: yarn
    - run: yarn typecheck
    - run: yarn lint
      if: ${{ success() || failure() }}
    - run: yarn test:coverage
      if: ${{ success() || failure() }}
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: [check]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: 'yarn.lock'
    - run: yarn
    - run: yarn build
    - run: ruby generate-exports.rb && git diff
    - uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ secrets.NPM_TOKEN }}
        dry-run: ${{ github.event_name != 'push' }}
